MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once today. Is that okay?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! My Pokémon totally rules!\n"
	.string "It's cooler than any Pokémon!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the CHAIRMAN\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "SWAGGER to a Pokémon of yours.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which Pokémon wants to\n"
	.string "learn how to SWAGGER?$"

MoveTutor_Text_SwaggerTaught:
	.string "I'll just praise my Pokémon from now\n"
	.string "on without the swagger.$"

MoveTutor_Text_RolloutTeach:
	.string "Did you know that you can go from\n"
	.string "here a long way in that direction\l"
	.string "without changing direction?\p"
	.string "I might even be able to roll\n"
	.string "that way.\p"
	.string "Do you think your Pokémon will\n"
	.string "want to roll, too?\p"
	.string "I can teach one the move ROLLOUT\n"
	.string "if you'd like.$"

MoveTutor_Text_RolloutDeclined:
	.string "You don't need to be shy about it.\n"
	.string "Let's roll!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the Pokémon looked like me.$"

MoveTutor_Text_RolloutTaught:
	.string "Rolling around in the grass makes me\n"
	.string "happy. Come on, let's roll!$"

MoveTutor_Text_FuryCutterTeach:
	.string "There's a move that gets stronger\n"
	.string "when you keep using it in a row.\p"
	.string "It's a BUG-type move, and it is\n"
	.string "wickedly cool.\p"
	.string "It's called FURY CUTTER.\n"
	.string "Want me to teach it to a Pokémon?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "We're not on the same wavelength.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay!\n"
	.string "Show me which Pokémon I should teach.$"

MoveTutor_Text_FuryCutterTaught:
	.string "I get a thrill watching to see if\n"
	.string "the move keeps hitting in succession!$"

MoveTutor_MimicTeach:
	.string "Ah, young one!\p"
	.string "I am also a young one, but I mimic\n"
	.string "the styles and speech of the elderly\l"
	.string "folks of this town.\p"
	.string "What do you say, young one?\n"
	.string "Would you agree to it if I were to\l"
	.string "offer to teach the move MIMIC?$"

MoveTutor_MimicDeclined:
	.string "Oh, boo! I wanted to teach MIMIC\n"
	.string "to your Pokémon!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! And so I shall!\n"
	.string "Let me see the Pokémon\l"
	.string "you wish me to teach.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIC is a move of great depth.\p"
	.string "Could you execute it to perfection\n"
	.string "as well as me…?$"

MoveTutor_Text_MetronomeTeach:
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if there were\n"
	.string "a spell that made money appear when\l"
	.string "you waggle a finger?\p"
	.string "If you want, I can teach your Pokémon\n"
	.string "the move METRONOME.\p"
	.string "Money won't appear, but your Pokémon\n"
	.string "will waggle a finger. Yes?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! I'll teach it!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_MetronomeTaught:
	.string "When a Pokémon waggles its finger\n"
	.string "like a METRONOME, all sorts of nice\l"
	.string "things happen.\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! My wife relies on HIDDEN\n"
	.string "POWER to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and Sleep Talk.\p"
	.string "I can teach your Pokémon how to\n"
	.string "Sleep Talk instead. Interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with HIDDEN POWER, too…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an appreciative child!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I Sleep Talk…$"

MoveTutor_Text_SubstituteTeach:
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if there were more than just one me\l"
	.string "so I could enjoy all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a Pokémon learn SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\p"
	.string "A Pokémon can make a copy of\n"
	.string "itself using it, you know.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Giggle…\n"
	.string "Which Pokémon do you want me to\l"
	.string "teach SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught:
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type Trainer,\n"
	.string "so I can't win at the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "Pokémon DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "What? You do? You're a good person!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to win at the MOSSDEEP GYM\n"
	.string "using that DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "SOOTOPOLIS's GYM LEADER is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a DOUBLE-EDGE.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your Pokémon\n"
	.string "the move DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Even you rejected me…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, which Pokémon should I teach\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach EXPLOSION to your Pokémon!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An EXPLOSION it is!\n"
	.string "Which Pokémon wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught Pokémon\n"
	.string "how to use EXPLOSION, but I've yet\l"
	.string "to ignite my own EXPLOSION…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"

MoveTutor_Text_TrickRoomTeach:
	.string "I lost all my coins on these slots.\p"
	.string "The only thing I have left to my\n"
	.string "name is my tricky technique.\p"
	.string "With it, slow Pokémon get to move\n"
	.string "before faster Pokémon.\p"
	.string "I was hoping to use it to make the\n"
	.string "slots slower, but there are eyes\l"
	.string "all over this place…\p"
	.string "How about I teach you my technique\n"
	.string "for a measly 50 coins?$"

MoveTutor_Text_TrickRoomDeclined:
	.string "Humph! Fine, but you can't make\n"
	.string "more coins without a little investing.$"

MoveTutor_Text_TrickRoomWhichMon:
	.string "Right. Which Pokémon want to learn\n"
	.string "this tricky technique?$"

MoveTutor_Text_TrickRoomTaught:
	.string "Best of luck to you on your games\n"
	.string "kid.\p"
	.string "Heh heh…\p"
	.string "Time to win my big break.$"

MoveTutor_Text_NaturalGiftTeach:
	.string "They say that plants grow up faster\n"
	.string "and stronger if you speak to them.\p"
	.string "So I'm here giving these berries\n" 
	.string "plenty of encouragement.\p"
	.string "The old folks say I have a gift but\n"
	.string "I just want nature to flourish…\p"
	.string "Why don't I teach one of your\n"
	.string "Pokémon my natural gift?$"

MoveTutor_Text_NaturalGiftDeclined:
	.string "Oh? That's ok…\n"
	.string "I'll be here if you need me.$"

MoveTutor_Text_NaturalGiftWhichMon:
	.string "Which Pokémon should learn to grant\n"
	.string "natures gift?$"

MoveTutor_Text_NaturalGiftTaught:
	.string "Phew! I'm spent.\p"
	.string "I think I'll just sit and listen\n"
	.string "to the berries for a little bit.$"

MoveTutor_Text_FlingTeach:
	.string "Huh?…\p"
	.string "Oh hey.\p"
	.string "I'm just flinging sticks into the\n"
	.string "lake to watch them float.\p"
	.string "I always fling sticks into the\n"
	.string "lake when I'm feeling moody.\p"
	.string "Are you here because you're\n"
	.string "feeling moody too?\p"
	.string "I can teach you how to fling\n"
	.string "stuff, if you want?$"

MoveTutor_Text_FlingDeclined:
	.string "Humph. Fine.$"

MoveTutor_Text_FlingWhichMon:
	.string "Which Pokémon should learn to fling\n"
	.string "stuff?$"

MoveTutor_Text_FlingTaught:
	.string "Now we can fling stuff together\n"
	.string "I guess.\p"
	.string "Oh… but stay away from my sticks.$"

MoveTutor_Text_ScorchingSandsTeach:
	.string "I'm practicing guitar in the\n"
	.string "desert because it's totally metal!\p"
	.string "I'm going to shred up these sands\n"
	.string "and set them ablaze with the fire\l"
	.string "in my heart!\p"
	.string "If you wanna shred with me, you've\n"
	.string "got to set your heart ablaze too!\p"
	.string "How about I teach you?$"

MoveTutor_Text_ScorchingSandsDeclined:
	.string "Nah? That's not very metal of\n"
	.string "you mann…$"

MoveTutor_Text_ScorchingSandsWhichMon:
	.string "Yeah! Who wants to set the sands\n"
	.string "ablaze in your party?$"

MoveTutor_Text_ScorchingSandsTaught:
	.string "Righteous! Get practicing mann!\p"
	.string "Maybe one day you can shred as\n"
	.string "hard as me, little dude!$"

MoveTutor_Text_DualChopTeach:
	.string "Chop! Chop!\p"
	.string "Hm?…\p"
	.string "Oh hey, kid.\n"
	.string "Best keep a safe distance.\p"
	.string "I'm cutting back these trees\n"
	.string "with my Dual Chop technique!\p"
	.string "… … …\p"
	.string "Hm? You want to learn my Dual\n"
	.string "Chop technique kid?$"

MoveTutor_Text_DualChopDeclined:
	.string "Yeah, best keep this work to\n"
	.string "the professionals.$"

MoveTutor_Text_DualChopWhichMon:
	.string "Which Pokémon is going to be\n"
	.string "doing the work, kid?$"

MoveTutor_Text_DualChopTaught:
	.string "Chop! Chop!\p"
	.string "Work is never done around\n"
	.string "these parts.$"

MoveTutor_Text_EarthPowerTeach:
	.string "When continental plates collide\n"
	.string "the power of the earth forces the\l"
	.string "land up into a peak.\p"
	.string "We call those mountains!\p"
	.string "Isn't the power of earth just\n"
	.string "amazing?\p"
	.string "Would you like to learn how to\n"
	.string "conjure the Power of Earth?$"

MoveTutor_Text_EarthPowerDeclined:
	.string "No? Guess I'll keep my earth\n"
	.string "knowledge to myself…$"

MoveTutor_Text_EarthPowerWhichMon:
	.string "Which Pokémon wants to share in\n"
	.string "the Power of Earth?$"

MoveTutor_Text_EarthPowerTaught:
	.string "Meteor Falls and Mt. Pyre form\n"
	.string "a mountain range where the plates\l"
	.string "collide.\p"
	.string "Fascinating, right?$"

MoveTutor_Text_GrassKnotTeach:
	.string "Hihi! I'm playing in the grass.\p"
	.string "It's fun to make daisy chains\n"
	.string "like this!\p"
	.string "To do it, you have to tie the\n"
	.string "stems up like this!\p"
	.string "Do you want to learn how to make\n"
	.string "Grass Knots for daisy chains?$"

MoveTutor_Text_GrassKnotDeclined:
	.string "No? Your loss!$"

MoveTutor_Text_GrassKnotWhichMon:
	.string "Which Pokémon wants to make\n"
	.string "daisy chains for you?$"

MoveTutor_Text_GrassKnotTaught:
	.string "WooHoo!\p"
	.string "It's fun to play in the grass.$"

MoveTutor_Text_RecycleTeach:
	.string "I'm collecting bits of trash\n"
	.string "that wash up on this path.\p"
	.string "It cleans up the environment\n"
	.string "and the trash can be Recycled\l"
	.string "into something useful!\p"
	.string "Want me to teach you and your\n"
	.string "Pokémon how to Recycle?$"

MoveTutor_Text_RecycleDeclined:
	.string "Oh dear… double the work\n"
	.string "for me then…$"

MoveTutor_Text_RecycleWhichMon:
	.string "Which Pokémon wants to do\n"
	.string "some Recycling?$"

MoveTutor_Text_RecycleTaught:
	.string "Fantastic! Now you can clean up\n"
	.string "and make useful things too!$"

MoveTutor_Text_DragonMasterIntroduction:
	.string "Greetings. I am the Dragon type\n"
	.string "Master.\p"
	.string "I am versed in some of the strongest\n"
	.string "Dragon techniques ever known.$"

MoveTutor_Text_DragonMasterSquabble:
	.string "Of course that Fighting type\n"
	.string "“Master” doesn't get it.\p"
	.string "Dragon types are far beyond them\n"
	.string "in terms of Power…$"

MoveTutor_Text_DragonMasterChallenge:
	.string "If you can defeat me, I'll teach\n"
	.string "you a true, Dragon technique.$"

MoveTutor_Text_DragonMasterDefeat:
	.string "Power worthy of the dragon!$"

MoveTutor_Text_DragonMasterWhichMove:
	.string "You have proven yourself to me.\p"
	.string "Which Dragon technique would you\n"
	.string "care to learn?$"

MoveTutor_Text_DragonMasterDeclined:
	.string "To learn such a powerful technique\n"
	.string "requires potential.\p"
	.string "Return when you are ready to learn\n"
	.string "again.$"

MoveTutor_Text_DragonMasterWhichMon:
	.string "Which Pokémon will learn such a\n"
	.string "powerful technique?$"

MoveTutor_Text_DragonMasterTaught:
	.string "Return when you are ready to learn\n"
	.string "again.$"

MoveTutor_Text_FightingMasterIntroduction:
	.string "Greetings. I am the Fighting\n"
	.string "type Master.\p"
	.string "I am trained in some of the toughest\n"
	.string "Fighting styles ever known.$"

MoveTutor_Text_FightingMasterSquabble:
	.string "That Dragon “Master” wouldn't know\n"
	.string "power if it smacked him.\p"
	.string "True strength comes from Fighting\n"
	.string "spirit!$"

MoveTutor_Text_FightingMasterChallenge:
	.string "If you can bring me down, I'll teach\n"
	.string "you a true, Fighting technique.$"

MoveTutor_Text_FightingMasterDefeat:
	.string "Huahahah! Yes!\n"
	.string "A truly indomitable spirit!$"

MoveTutor_Text_FightingMasterWhichMove:
	.string "Your spirit is absolutely ablaze with\n"
	.string "Fighting power!\p"
	.string "Which Fighting style do you want me\n"
	.string "to teach you?$"

MoveTutor_Text_FightingMasterDeclined:
	.string "Learning these Fighting styles takes\n"
	.string "pure determination!\p"
	.string "Come back when you're ready to work\n"
	.string "to your core!$"

MoveTutor_Text_FightingMasterWhichMon:
	.string "Which Pokémon has the guts to learn\n"
	.string "this powerful Fighting style?$"

MoveTutor_Text_FightingMasterTaught:
	.string "Come back when you're ready to work\n"
	.string "to your core again!$"
