gText_GTSLadyDoYouWantToUse::
    .string "Would you like to use the\n"
    .string "GTS service?$"

gText_WonderLadyDoYouWantToUse::
    .string "Would you like to use the\n"
    .string "Wonder Trade service?$"

gText_PleaseSelectAPokemon::
    .string "Please select a Pokémon\n"
    .string "to be traded.$"

gText_GTSLadyAreYouSure::
    .string "Are you sure you want to put\n"
    .string "{STR_VAR_1} onto the GTS?$"

gText_GTSLadyHeresCode::
    .string "Here's your code:\n"
    .string "{STR_VAR_2}$"

gText_GTSLadyEnterCodeNow::
    .string "Would you like to enter\n"
    .string "a GTS code now?$"

gText_GTSLadyTooFewPokemon::
    .string "Sorry, you need more than\n"
    .string "one Pokémon to use the\l"
    .string "GTS service.$"
