gText_GTSLadyDoYouWantToUse::
    .string "Would you like to use the\n"
    .string "GTS code service?$"

gText_WonderLadyDoYouWantToUse::
    .string "Would you like to use the\n"
    .string "Wonder Trade service?$"

gText_GTSLadyExplainService::
    .string "The GTS code service allows you\n"
    .string "to trade Pokémon with anybody,\l"
    .string "anywhere in the world!\p"
    .string "When you deposit a Pokémon I will\n"
    .string "give you a code for you to share\l"
    .string "with your trade partner.\p"
    .string "When you enter a code from a trade\n"
    .string "partner, you will recieve their\l"
    .string "Pokémon via our service!\p"
    .string "Bear in mind that certain elements\n"
    .string "of a Pokémon may change when they\l"
    .string "enter the GTS network.\p"
    .string "Specifically, Pokémon's effort values,\n"
    .string "hyper training, and moves.$"

gText_WonderLadyExplainService::
    .string "The Wonder Trade service allows\n"
    .string "you to trade Pokémon with somebody,\l"
    .string "completely at random.\p"
    .string "What you get from a Wonder Trade\n"
    .string "will always be a surprise!\p"
    .string "The Pokémon come from all across the\n"
    .string "globe, so you may just find yourself\l"
    .string "with a rare species.\p"
    .string "Just be aware that there is no way\n"
    .string "to recover the Pokémon you trade away\l"
    .string "with our service.$"

gText_PleaseSelectAPokemon::
    .string "Please select a Pokémon to be\n"
    .string "traded.$"

gText_GTSLadyAreYouSure::
    .string "Are you sure you want to deposit\n"
    .string "{STR_VAR_2}?$"

gText_WonderLadyAreYouSure::
    .string "Are you sure you want to trade\n"
    .string "{STR_VAR_2}?$"

gText_ConnectingToGlobalNetwork::
    .string "Connecting to the Global Network.\n"
    .string "Please wait…$"

gText_GTSLadyWasDeposited::
    .string "{STR_VAR_2} was deposited\n"
    .string "onto the GTS.$"

gText_GTSLadyAlreadyOnTheGTS::
    .string "{STR_VAR_2} is alreading waiting\n"
    .string "in the GTS system.$"

gText_GTSWhatWouldYouLikeToDo::
    .string "What would you like to do?$"

gText_GTSLadyHeresCode::
    .string "Here's your GTS connect code:\n"
    .string "{STR_VAR_1}\l"
    .string "Please share it with your partner.$"

gText_GTSLadyPokemonRecieved::
    .string "Recieved {STR_VAR_2} from the GTS.$"

gText_GTSLadyTooFewPokemon::
    .string "Sorry, you need more than one\n"
    .string "Pokémon to use the GTS.$"

gText_GlobalPleaseComeAgain::
    .string "Please come again.$"
