gText_GTSLadyDoYouWantToUse::
    .string "Would you like to use the\n"
    .string "GTS code service?$"

gText_WonderLadyDoYouWantToUse::
    .string "Would you like to use the\n"
    .string "Wonder Trade service?$"

gText_PleaseSelectAPokemon::
    .string "Please select a Pokémon to be\n"
    .string "traded.$"

gText_GTSLadyAreYouSure::
    .string "Are you sure you want to deposit\n"
    .string "{STR_VAR_2}?$"

gText_WonderLadyAreYouSure::
    .string "Are you sure you want to trade\n"
    .string "{STR_VAR_2}?$"

gText_ConnectingToGlobalNetwork::
    .string "Connecting to the Global Network.\n"
    .string "Please wait…$"

gText_GTSLadyWasDeposited::
    .string "{STR_VAR_2} was deposited\n"
    .string "onto the GTS.$"

gText_GTSLadyAlreadyOnTheGTS::
    .string "{STR_VAR_2} is alreading waiting\n"
    .string "in the GTS system.$"

gText_GTSLadyHeresCode::
    .string "Here's your GTS connect code:\n"
    .string "{STR_VAR_1}\l"
    .string "Please share it with your partner.$"

gText_GTSLadyEnterCodeNow::
    .string "Would you like to enter a partner's GTS\n"
    .string "connect code now?$"

gText_GTSLadyPokemonRecieved::
    .string "Recieved {STR_VAR_2} from the GTS.$"

gText_GTSLadyTooFewPokemon::
    .string "Sorry, you need more than one\n"
    .string "Pokémon to use the GTS.$"

gText_GlobalPleaseComeAgain::
    .string "Please come again.$"
