Route102_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route103_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route104_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end

Route104_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route105_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route106_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route108_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route109_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route109_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route110_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route110_EventScript_ItemDireHit::
	finditem ITEM_DIRE_HIT
	end

Route110_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route111_EventScript_ItemTMSandstorm::
	finditem ITEM_TM_SANDSTORM
	end

Route111_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

Route111_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route111_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route111_EventScript_SmoothRock::
	finditem ITEM_SMOOTH_ROCK
	end

Route112_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route112_EventScript_Magmarizer::
	finditem ITEM_MAGMARIZER
	end

Route113_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

Route113_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route113_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route113_EventScript_ItemHeatRock::
	finditem ITEM_HEAT_ROCK
	end

Route113_EventScript_CrackedPot::
	finditem ITEM_CRACKED_POT
	end

Route114_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route114_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route114_EventScript_ItemEnergyPowder::
	finditem ITEM_ENERGY_POWDER
	end

Route115_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

Route115_EventScript_ItemTMFocusPunch::
	finditem ITEM_TM_FOCUS_PUNCH
	end

Route115_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route115_EventScript_ItemHealPowder::
	finditem ITEM_HEAL_POWDER
	end

Route115_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route116_EventScript_ItemXSpecial::
	finditem ITEM_X_SP_ATK
	end

Route116_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

Route116_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

Route116_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route116_EventScript_Protector::
	finditem ITEM_PROTECTOR
	end

Route117_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route117_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route118_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route119_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route119_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route119_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

Route119_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route119_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemHyperPotion2::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemElixir2::
	finditem ITEM_ELIXIR
	end

Route120_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route120_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route120_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

Route120_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route121_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route123_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

Route123_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route123_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route123_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route123_EventScript_ItemRevivalHerb::
	finditem ITEM_REVIVAL_HERB
	end

Route124_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route126_EventScript_ItemGreenShard::
	finditem ITEM_GREEN_SHARD
	end

Route127_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route127_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route127_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route133_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route133_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route133_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

Route134_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route134_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

VerdantForest_EventScript_ItemTM53::
	finditem ITEM_TM53
	end

Route103_EventScript_ItemTM54::
	finditem ITEM_TM54
	end

Route119_EventScript_ItemTM55::
	finditem ITEM_TM55
	end

MagmaHideout_3F_2R_EventScript_ItemTM56::
	finditem ITEM_TM56
	end

ColdStorage_EventScript_TM_57::
	finditem ITEM_TM57
	end

Route134_EventScript_ItemTM59::
	finditem ITEM_TM59
	end

FieryCavern_EventScript_ItemTM61::
	finditem ITEM_TM61
	end

PetalburgWoods_EventScript_ItemTM62::
	finditem ITEM_TM62
	end

SlateportCity_Factory_EventScript_ItemTM63::
	finditem ITEM_TM63
	end

NewMauville_Inside_EventScript_ItemTM64::
	finditem ITEM_TM64
	end

Route116_EventScript_ItemTM66::
	finditem ITEM_TM66
	end

Route120_EventScript_ItemTM71::
	finditem ITEM_TM71
	end

Route115_EventScript_ItemTM72::
	finditem ITEM_TM72
	end

OutsetPath_EventScript_ItemTM73::
	finditem ITEM_TM73
	end

PetalburgCity_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

PetalburgCity_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

PetalburgCity_EventScript_ItemBottleCap::
	finditem ITEM_BOTTLE_CAP
	end

MauvilleCity_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

MauvilleCity_EventScript_Electirizer::
	finditem ITEM_ELECTIRIZER
	end

RustboroCity_EventScript_ItemXDefend::
	finditem ITEM_X_DEFENSE
	end

RustboroCity_EventScript_FluffyTail::
	finditem ITEM_FLUFFY_TAIL
	end

LilycoveCity_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

MossdeepCity_EventScript_ItemNetBall::
	finditem ITEM_NET_BALL
	end

PetalburgWoods_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

PetalburgWoods_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

PetalburgWoods_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

RusturfTunnel_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

RusturfTunnel_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

GraniteCave_1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

GraniteCave_B1F_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

GraniteCave_B1F_EventScript_ItemTM69::
	finditem ITEM_TM69	
	end

GraniteCave_B2F_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

GraniteCave_B2F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

JaggedPass_EventScript_ItemBurnHeal::
	finditem ITEM_BURN_HEAL
	end

FieryPath_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

FieryPath_EventScript_ItemTMToxic::
	finditem ITEM_TM_TOXIC
	end

MeteorFalls_1F_1R_EventScript_ItemTMIronTail::
	finditem ITEM_TM_IRON_TAIL
	end

MeteorFalls_1F_1R_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

MeteorFalls_1F_1R_EventScript_ItemTM75::
	finditem ITEM_TM75
	end

MeteorFalls_B1F_2R_EventScript_ItemTMDragonClaw::
	finditem ITEM_TM_DRAGON_CLAW
	end

NewMauville_Inside_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

NewMauville_Inside_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
	finditem ITEM_DIVE_BALL
	end

AbandonedShip_Room_B1F_EventScript_ItemTMIceBeam::
	finditem ITEM_TM_ICE_BEAM
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
	finditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
	finditem ITEM_LUXURY_BALL
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
	finditem ITEM_SCANNER
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTMRainDance::
	finditem ITEM_TM_RAIN_DANCE
	end

ScorchedSlab_EventScript_ItemTMSunnyDay::
	finditem ITEM_TM_SUNNY_DAY
	end

SafariZone_Northwest_EventScript_ItemTMSolarBeam::
	finditem ITEM_TM_SOLAR_BEAM
	end

SafariZone_North_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

SafariZone_Southwest_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

SafariZone_Northeast_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

SafariZone_Southeast_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

MtPyre_2F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

MtPyre_3F_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

MtPyre_4F_EventScript_ItemSeaIncense::
	finditem ITEM_SEA_INCENSE
	end

MtPyre_5F_EventScript_ItemLaxIncense::
	finditem ITEM_LAX_INCENSE
	end

MtPyre_6F_EventScript_ItemTMShadowBall::
	finditem ITEM_TM_SHADOW_BALL
	end

MtPyre_Exterior_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

MtPyre_Exterior_EventScript_ItemTMSkillSwap::
	finditem ITEM_TM_SKILL_SWAP
	end

AquaHideout_B1F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL
	end

AquaHideout_B1F_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

AquaHideout_B1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

AquaHideout_B2F_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route119_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

Route119_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTMHail::
	finditem ITEM_TM_HAIL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

SeafloorCavern_Room9_EventScript_ItemTMEarthquake::
	finditem ITEM_TM_EARTHQUAKE
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
	finditem ITEM_ORANGE_MAIL
	end

Route110_TrickHousePuzzle1_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
	finditem ITEM_WAVE_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemIceStone::
	finditem ITEM_ICE_STONE
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
	finditem ITEM_SHADOW_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
	finditem ITEM_WOOD_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_DuskStone::
	finditem ITEM_DUSK_STONE
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
	finditem ITEM_MECH_MAIL
	end

Route110_TrickHousePuzzle4_EventScript_ItemSunStone::
	finditem ITEM_SUN_STONE
	end

Route110_TrickHousePuzzle5_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
	finditem ITEM_GLITTER_MAIL
	end

Route110_TrickHousePuzzle6_EventScript_ItemShinyStone::
	finditem ITEM_SHINY_STONE
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
	finditem ITEM_TROPIC_MAIL
	end

Route110_TrickHousePuzzle7_EventScript_ItemDawnStone::
	finditem ITEM_DAWN_STONE
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
	finditem ITEM_BEAD_MAIL
	end

VictoryRoad_1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

VictoryRoad_1F_EventScript_ItemTM52::
	finditem ITEM_TM52
	end

VictoryRoad_B1F_EventScript_ItemTMPsychic::
	finditem ITEM_TM_PSYCHIC
	end

VictoryRoad_B1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

VictoryRoad_B2F_EventScript_ItemTM65::
	finditem ITEM_TM65
	end

ArtisanCave_B1F_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

ArtisanCave_1F_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

MagmaHideout_1F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

MagmaHideout_3F_1R_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax::
	finditem ITEM_PP_MAX
	end

MagmaHideout_4F_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

Hidden_Grotto_3_EventScript_Relic_Band::
	finditem ITEM_RELIC_BAND
	end

Hidden_Grotto_4_EventScript_Leek::
	finditem ITEM_LEEK
	end

Hidden_Grotto_5_EventScript_Relic_Vase::
	finditem ITEM_RELIC_VASE
	end

Hidden_Grotto_9_EventScript_Thick_Club::
	finditem ITEM_THICK_CLUB
	end

Hidden_Grotto_10_EventScript_Relic_Statue::
	finditem ITEM_RELIC_STATUE
	end

Hidden_Grotto_10_EventScript_Light_Ball::
	finditem ITEM_LIGHT_BALL
	end

Hidden_Grotto_14_EventScipt_Lucky_Punch::
	finditem ITEM_LUCKY_PUNCH
	end

Hidden_Grotto_15_EventScript_Relic_Statue::
	finditem ITEM_RELIC_STATUE
	end

Hidden_Grotto_15_EventScript_Relic_Band::
	finditem ITEM_RELIC_BAND
	end

Hidden_Grotto_16_EventScript_Galarica_Wreath::
	finditem ITEM_GALARICA_WREATH
	end

Hidden_Grotto_18_EventScript_Spell_Tag::
	finditem ITEM_SPELL_TAG
	end

Hidden_Grotto_21_EventScript_Relic_Crown::
	finditem ITEM_RELIC_CROWN
	end

Hidden_Grotto_23_EventScript_Reaper_Cloth::
	finditem ITEM_REAPER_CLOTH
	end

Hidden_Grotto_24_EventScript_Relic_Band::
	finditem ITEM_RELIC_BAND
	end

Hidden_Grotto_24_EventScript_Relic_Vase::
	finditem ITEM_RELIC_VASE
	end

Hidden_Grotto_24_EventScript_Relic_Statue::
	finditem ITEM_RELIC_STATUE
	end

Hidden_Grotto_20_EventScript_Relic_Crown::
	finditem ITEM_RELIC_CROWN
	end

Hidden_Grotto_20_EventScript_Soul_Dew::
	finditem ITEM_SOUL_DEW
	end

Hidden_Grotto_25_EventScript_Relic_Crown::
	finditem ITEM_RELIC_CROWN
	end

RusturfTunnel_2F_EventScript_BottleCap::
	finditem ITEM_BOTTLE_CAP
	end

RusturfCliff_EventScript_PrettyFeather::
	finditem ITEM_PRETTY_FEATHER
	end

Route131_Underwater_EventScript_TM70::
	finditem ITEM_TM70
	end
